{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.existingClaim) }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ template "cosmos.fullname" . }}
  labels:
{{ include "cosmos.labels" . | indent 4 }}
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: {{ .Values.persistentVolume.size }}
{{- if .Values.persistentVolume.volumeConfig.nfs }}
  nfs:
{{ toYaml .Values.persistentVolume.volumeConfig.nfs | indent 4 }}
{{- if .Values.persistentVolume.volumeConfig.mountOptions }}
  mountOptions:
  {{- range split "," .Values.persistentVolume.volumeConfig.mountOptions }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- else }}
{{ toYaml .Values.persistentVolume.volumeConfig | indent 2 }}
{{- end }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ template "cosmos.storageclass.name" . }}
{{- end }}
