{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "cosmos.fullname" . }}
  labels:
{{ include "cosmos.labels" . | indent 4 }}
spec:
  accessModes:
{{- range .Values.persistentVolume.accessModes }}
    - {{ . | quote }}
{{- end }}
  resources:
    requests:
      storage: {{ .Values.persistentVolume.size | quote }}
  storageClassName: {{ template "cosmos.storageclass.name" . }}
  volumeName: {{ template "cosmos.fullname" . }}
{{- end }}
