{{- if and .Values.persistentVolume.enabled (not .Values.persistentVolume.storageClass) }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ template "cosmos.fullname" . }}
  labels:
{{ include "cosmos.labels" . | indent 4 }}
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
{{- end -}}
