{{- if not .Values.rclone.remote.existingSecret -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "cosmos.rclone.fullname" . }}
  labels:
{{ include "cosmos.labels" . | indent 4 }}
type: Opaque
data:
  accessKey: {{ .Values.rclone.remote.accessKey | b64enc }}
  secretKey: {{ .Values.rclone.remote.secretKey | b64enc }}
{{- end -}}
